name: Print Rull Request Context
on:
  workflow_dispath:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ toJSON(github.event) }}"
