name: Testing React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependecies
        run: npm ci
      - name: Testing application
        run: npm run test
